name: Docker Build

on:
  push:
    branches:
      - prod
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - "**.md"
      - "tests/**"
    tags:
      - "v*.*.*"
  workflow_dispatch:
  workflow_call:

jobs:
  # Builds and pushes the Docker image

  # Good practice 1: Proper secret management using GitHub Secrets

  docker-build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    # Good practice 2: Docker build runs only for trusted actors (not bots)

    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[[skip docker build]]') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        run: |
          repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "TAG=ghcr.io/${repo}" >> $GITHUB_OUTPUT

      - name: Build and push release image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/release/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.TAG }}:latest
            ${{ steps.meta.outputs.TAG }}:${{ github.sha }}

  deploy:
    name: Deploy
    needs: docker-build
    runs-on: ubuntu-latest

    # Good practice 3: SSH deploy uses secrets, not hardcoded credentials

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Write OpenVPN config
        run: |
          cat > client.ovpn <<'OVPN'
          ${{ secrets.OPENVPN }}
          OVPN
          chmod 600 client.ovpn
          if [[ -n "${{ secrets.OPENVPN_USER }}" && -n "${{ secrets.OPENVPN_PASS }}" ]]; then
            printf '%s\n%s\n' "${{ secrets.OPENVPN_USER }}" "${{ secrets.OPENVPN_PASS }}" > auth.txt
            chmod 600 auth.txt
            if ! grep -q '^auth-user-pass' client.ovpn; then
              echo "auth-user-pass auth.txt" >> client.ovpn
            else
              sed -i 's/^auth-user-pass$/auth-user-pass auth.txt/' client.ovpn
            fi
          fi

      - name: Start OpenVPN
        run: |
          sudo openvpn --config client.ovpn --daemon --writepid /tmp/openvpn.pid
          for i in {1..30}; do
            ip a show dev tun0 && break
            sleep 2
          done
          ip a show dev tun0 || (echo "tun0 not up" && exit 1)

      - name: Set repository tag
        id: repo-tag
        run: |
          repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "TAG=ghcr.io/${repo}" >> $GITHUB_OUTPUT

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          use_insecure_cipher: false
          timeout: 60s
          command_timeout: 60s
          script: |
            sudo -n /data/scripts/deploy.sh ${{ steps.repo-tag.outputs.TAG }} ${{ secrets.USER }} ${{ secrets.PAT }}
