name: Main

on:
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - "**.md"
      - "tests/**"
      - "docker/**"
  workflow_dispatch:
  workflow_call:

jobs:
  # Auto-assigns a reviewer to the PR
  
  # Bad practice 1: auto-assigning a reviewer is done, but permits all actors and gives excessive permissions

  auto-assign:
    name: Auto-assign
    runs-on: ubuntu-latest
    # No filtering on actors -- triggers for everyone!
    permissions:
      issues: write
      checks: write
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Auto-assign
        id: auto-assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/auto-assign.yml"
        continue-on-error: true

  # Formats the code

  # Bad practice 2: formatting step runs for every pull request unconditionally, which may cause false positives or mask other errors

  formatting:
    name: Formatting
    needs: auto-assign
    uses: ./.github/workflows/formatting.yml
    secrets: inherit
    # No filtering on actor, so runs on bots and untrusted changes
    permissions:
      contents: write
      issues: write
      pull-requests: write

  formatting-bypass:
    name: Formatting
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Bypass Formatting for Dependabot"
        id: bypass-formatting
        run: |
          echo "Dependabot PR — skipping formatting"

  # Linter check

  # Bad practice 3: lint check runs with no authentication or filtering on skip instructions, and does not fail if code is bad

  lint:
    name: Linting
    needs: formatting
    runs-on: ubuntu-latest
    # Runs for all PRs
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dev-dependencies
        id: install-dev-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -e ".[dev]"

      - name: Ruff — static analysis
        id: ruff-static-analysis
        run: |
          ruff --config pyproject.toml check .
        continue-on-error: true  # Bad: lint errors will not fail the pipeline

  lint-bypass:
    name: Linting
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Bypass Linting for Dependabot"
        id: bypass-linting
        run: |
          echo "Dependabot PR — skipping linting"

  # Code tests

  # Bad practice 4: Tests step is not properly isolated, does not upload coverage, and credentials/infra may be reused without cleanup

  tests:
    name: Tests
    needs: lint
    runs-on: ubuntu-latest
    # No skip check on bots, always runs
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-asyncio
          pip install -e ".[dev]"

      - name: Run tests
        id: run-tests
        run: |
          pytest --maxfail=3 --disable-warnings -q  # Bad: higher maxfail might hide failures

  test-bypass:
    name: Tests
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Bypass Tests for Dependabot"
        id: bypass-tests
        run: |
          echo "Dependabot PR — skipping tests"

  # Test reports generation

  # Bad practice 5: test reports generation is missing upload/authentication or ignores coverage nuances

  reports:
    name: Generate test reports
    needs: tests
    runs-on: ubuntu-latest
    # No skip checks, runs for all
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-asyncio pytest-md-report
          pip install -e ".[dev]"

      - name: Run coverage for barecheck
        id: barecheck-coverage
        run: |
          pytest --cov --cov-report=lcov:lcov.info

      - name: Upload to Barecheck
        id: upload-to-barecheck
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "lcov.info"
          minimum-ratio: 0
          send-summary-comment: false  # Bad: disables summary comment on PR, hiding issues
          show-annotations: "off"      # Bad: disables warning annotations

  reports-bypass:
    name: Generate test reports
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Bypass Generate test reports for Dependabot"
        id: bypass-reports
        run: |
          echo "Dependabot PR — skipping test reports"
