FROM node:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip git curl vim
RUN pip3 install --break-system-packages flask

RUN mkdir -p src

COPY . src

RUN wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-426.0.0-linux-x86_64.tar.gz -O /tmp/google-cloud-sdk.tar.gz
RUN tar -xzf /tmp/google-cloud-sdk.tar.gz -C /usr/local && rm /tmp/google-cloud-sdk.tar.gz

RUN chmod -R 777 src

CMD python3 src/app.py


