apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx.volume.name" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      include mime.types;

      upstream portal {
        server {{ template "portal.fullname" . }}:{{ .Values.portal.service.servicePortAccess }};
      }
      upstream importer {
        server {{ template "portal.fullname" . }}:{{ .Values.portal.service.servicePortImport }}; 
      }

      server {
        set $domain ${DOMAIN};
        server_name ${domain} www.${domain};
        underscores_in_headers on;
        access_log  off;
        listen 80;

        client_max_body_size 4G;

        set $ROOT_DIR /var/www;
        set $BACKEND_DIR /usr/src/app;

        location / {
          root $ROOT_DIR/front;
          try_files $uri $uri/ /index.html;

          location /assets/ {
            add_header Cache-Control max-age=31536000;
            }
          }

          location = /api/v1/scan/import/   {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass  http://importer;
          }

          location ~ ^/(admin|swagger|api/v1|oauth2/callback)/* {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass  http://portal;
          }

          location /static/ {
            alias $BACKEND_DIR/static/;
          }

          location /media/ {
            alias $BACKEND_DIR/media/;
          }
        }
      }