{{- if .Values.webhook.ingress.enabled -}}
{{- $servicePort := .Values.portal.frontend.containerPorts.http -}}
{{- $path := .Values.webhook.ingress.path -}}
{{- $pathType := .Values.webhook.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "portal.fullname" . }}-webhook-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "portal.labels" (dict "context" . "component" .Values.portal.name "name" .Values.portal.name) | nindent 4 }}
    {{- with .Values.webhook.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.webhook.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.webhook.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- if .Values.webhook.ingress.host }}
    {{- $host := .Values.webhook.ingress.host }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ template "portal.fullname" . }}
                port:
                  number: {{ $servicePort }}
  {{- else }}
    - http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ template "portal.fullname" . }}
                port:
                  number: {{ $servicePort }}
  {{- end -}}
{{- end -}}